certoperations.js

add subjectAltName with DNS and IP entry type when necessary according to passed commonName in "IssueWebServerCertificate" function

Fix annoying Google Chrome warning about invalid certificate

---

meshcentral.js

#324 
Changing to the decimal representation allows this command to work properly:
node meshcentral --admin <your existing user name in format domain/username or username>
Does the default DB/ node / js not support hex literals?
This means that it is possible to for me to create an administrator user by alternate means to the first user policy. ( Which was not workin g for me )

Workaround / fix

---

readme.md

Github doesn't render markdown in txt files, so readme.txt should be renamed to readme.md so that it will.
This PR also makes some improvements to the markdown present in the readme.

Rename readme.txt to readme.md and improve markdown

---

agents/meshcore.js
agents/modules_meshcore/apfclient.js
apfserver.js

This patch is to add apfclient at meshagent and to add console command to enable apf. Currently apf command is to check the status of apf tunnel, apf on to activate apf tunnel and apf off to terminate apf tunnel.
Please review.

Adding console apf command

---

agents/meshcore.js
agents/meshcore.min.js
meshuser.js

Expand pluginHandler support to communicate with browser<->server over the control channel. (Aids in gathering server-side plugin specific data).
Expand plugin functionality on agents to get plugin commands as their own action. (Aids in sending data to an agent from the server without abusing existing console msg's).

Expand pluginHandler support for plugins

---

agents/meshcore.js
agents/meshcore.min.js

Currently, using the terminal functionality will only make the current shell interactive. This means that sub-shells will not have the usual "$" or other values for $PS1, CTRL+C will kill any sub-shells created and backspace and other special key combinations won't work correctly.
This issue occurs whenever a sub-shell is started, including switching users (which is very bad because of the above mentioned problems). Using a PTY fixes this problem completely, by making programs (like bash) think they're running in an interactive terminal.
(PS: I spent a lot of time figuring this out because its REALLY frustrating and DESTROYS the user experience)

Use PTY if python is available

---

views/default.handlebars

Looks like something in the pull request / rework caused the denied plugin actions to check based on the index rather than the actual values (so no cant_actions are actually accounted for). This compares the correct values and populates the options appropriately.

Fix available plugin actions

---

pluginHandler.js

Currently breaking versions comparisons for versions -a through -c (ASCII char val is 97, 98, 99) which appears to be a lower version than intended for version comparisons.
E.g. 0.4.4-z is evaluated as 0.4.4122 (z ASCII is 122) so a comparison with 0.4.5-a is 0.4.597, which appears to be lower in version. This PR pads the conversion from -alpha_char to 3 numbers so version 0.4.5-a would become 0.4.5097, thus satisfying an upgrade comparison correctly.

Fix MeshCentral version comparisons. 

---

pluginHandler.js
plugin_development.md
public/styles/style.css
views/default.handlebars

A couple small updates:
- OnStates for current plugin tab within the device page
- Move p19 styles to stylesheet from the default.handlebars
- Wait to update meshcore until after all plugins loaded, rather than after each plugin is loaded
- More intuitive registerPluginTab functionality / flexibility (with backward compat)

Plugin Tab OnStates / Better MeshCore processing

---

pluginHandler.js
views/default.handlebars

Show plugins tab in device tab only if plugins exists that use that functionality.
Note that while testing I was receiving "updateMapMarkers is not defined" in the console. Seems 
@Ylianst is working on some GeoLocation.
Satisfies #699

Show/Hide Plugins tab in device view

---

pluginHandler.js
views/default.handlebars

Hi @Ylianst ,
It looks like you refactored some plugin code using inline javascript variables for templating in the "IE11 Fixes" commit. I didn't realize that broke IE11, sorry!
While you were fixing it, quotes were removed from the plugin admin links, meaning javascript functions were called with the name of the plugin as variables instead of text. (e.g. goPlugin("eventlog", "Event Log"); became goPlugin(eventlog, Event Log);)
This fixes that, as well as the opportunity that a plugin may contain a single quote that would break it in the same fashion.

Plugin Admin Links Broken

---

pluginHandler.js

Move updateMeshCore call to when a plugin is disabled instead of removed, as the core should be modified when the plugin is disabled, not removed.

Fix updateMeshCore Call

---

translate/translate.json

{
"en": "Free",
"fr": "Libre",
"pt": "Livre",
"ja": "無料",
"cs": "Volné",
"nl": "Vrij",
"xloc": [
"default.handlebars->23->1281",
"default.handlebars->23->1283"
]
},
{
"en": "free",
"fr": "libre",
"pt": "Livre",
"ja": "無料",
"cs": "volné",
"nl": "vrij",
"xloc": [
"default.handlebars->23->1311"
]
},
can i schrik it too this? if so a can clean up the double lines of identical text
{
"en": "Free",
"fr": "Libre",
"pt": "Livre",
"ja": "無料",
"cs": "Volné",
"nl": "Vrij",
"xloc": [
"default.handlebars->23->1281",
"default.handlebars->23->1283"
"default.handlebars->23->1311"
]
},

new update translation file (dutch)

---

translate/translate.json

The group actions in My Devices overview screen were broken in the following language translations due to translation of an identifier as reported in #793 :
* de
* nl
* pt
The translations of the identifier have been reverted to the English original to mitigate the problem.
Final solution should be the removal of the identifier "DeviceCheckbox" from translatable strings.

Reenable broken group actions in My Devices overview screen

---

meshcentral.js
package.json

Meshcentral can now specify specific versions of dynamic dependencies and the module system will try to match said version automatically. This removes the need for the weird greenlock hacks and allows meshcentral to control dynamic modules similarly to package.json.
I also added otplib as a dependency, since it's required by default.

Improve the way dynamic dependencies work

---

agents/meshcore.js
views/xterm.handlebars

Some notes:
- Only works in PTYs. I couldn't get xterm.js to not do [this](https://user-images.githubusercontent.com/38938720/73110406-90357e80-3f06-11ea-8ee8-8d919883e5fb.png), even without dynamic resizing enabled.
- I removed the following line because it shouldn't even be called when not in terminal mode, + it didn't work for user terminal sessions: `                if (ws.httprequest.protocol == 1) { // Terminal`
Would be great if you could test this first. I tested this on my Manjaro Linux install, but you never know.

Add dynamic resizing support to xterm.js terminal

---

db.js

This pull request fixes two mistakes that I found in the syntax of the current `mongodump` command.
1. The command line flag `--url` does not exist; the correct flag is `--uri` ([source](https://docs.mongodb.com/manual/reference/program/mongodump/#cmdoption-mongodump-uri)).
2. The command line flags `--uri` and `--db` cannot be used together ([source](https://docs.mongodb.com/manual/reference/program/mongodump/#cmdoption-mongodump-db)).
This change should fix #717 and fix #885.

Fix mongodump command syntax

---

amtscanner.js

This to alleviate issue when AMT CIRA status unintentionally reset due to TCP check failure. We are seeing multiple instances where AMT connectivity state unintentionally set to offline because TCP check returned false because AMT device is in CIRA mode. 
We may need to add additional exception for checking for hybrid mode because amtscanner attempted to perform scan on device connected over the internet (behind NAT). We should only perform AMT TCP check if the source IP of MeshAgent connection is one of the IP of the interfaces reported by AMT (via MeshAgent).
CC: @matt-primrose @Ganeshr93 for review

Add existing CIRA connection exception from periodic AMT scanning.

---

translate/translate.json

the screenshot shows (circled) text not to be found
verified and not verified in the translate.json

language update 0.4.9-z

---

meshrelay.js
meshuser.js

Update server console command 'relays' to display friendly information
A small quality of life update for users who utilize relays so that the Server Console -> "relays" command outputs the user and peer device utilizing the connection.
I often use the "relays" command to see if my server is being used for relays (Work From Home) people before upgrading / restarting the service. Rather than just numbers (and backtracking from IP's to devices), this adds the user id and name of the node they are connected to.

Add metadata to the relay connection for user -> device tracking

---

agents/meshcore.js
public/scripts/agent-redir-ws-0.1.1.js
views/default.handlebars

2. Add latency to Remote Desktop view
Another quality of life update. I added a latency timer to the CreateAgentRedirect object that, once started, sends a control channel message every ~3 seconds to measure latency between the MC user and the client machine.
As an example (and probably one of the more useful places for it) I added the output to the Remote Desktop device tab- but it can be easily added to anywhere a CreateAgentRedirect is used to measure latency via `varName.latency.onUpdate([callbackFunc])`

1. Add latency timer and callback opportunity to CreateAgentRedirect

---

pluginHandler.js

Caught some plugin version checks failing with the new semver versions (which I love, btw). Thank you!

Fix plugin version compare for new semver numbers

---

pluginHandler.js

* pluginHandler.js: Removed superfluous ; to fix faulty substitution in minifying mode

Fix minifying renders MC 0.5.22+ unusable if enabled #1336

---

meshctrl.js
webserver.js

Hi,
I use LDAP for users, and unfortunately meshcentral does not import user mail address from the directory. Most directories have some sort of email attribute. This PR :
- adds the `ldapuserEmail` option that allows to choose wich LDAP attribute to use. default is `mail`
- supports multivalued mail attribute. if the attribute is multivalued, which is allowed in LDAP, it uses the firs email address returned
- adds email on first import
- updates email if it changes when user logs in (same as username)
I did some quick tests both with the test LDAP and  real LDAP server and so far, I did not  notice any problem.
I don't know what exactly the `domainValues` in meshctrl.js is for. Everything worked well without `ldapuseremail`beeing added to the list. This is in a separate commit so it's …

Import and update meshcental account  email from LDAP

---

meshrelay.js

Looking through some relay logs I noticed the IP addresses didn't match the start event, but were reversed.

From/to relay IP fix to match start event

---

agents/meshcmd.js

1. Running from the command line does not currently appear to support the serverUrl variable (thus requiring a meshaction.txt file). This fixes that.
2. Allow a generated authCookie to serve as a credentialed logon via meshcmd, versus using plaintext username/password for the routing function.
Note: Apologies in advance. For some reason GitHub thinks I rewrote the entire file on the second commit. Viewing in a local client appears to produce only the ~12 changes lines. 🤷‍♂️

Meshcmd Updates

---

public/robots.txt

As much as I enjoy googling to find everyone running MeshCentral servers and see how outdated some of them are... they probably shouldn't be listed!
Also referenced [here](https://github.com/Ylianst/MeshCentral/issues/1227#issuecomment-618667608), but figured I'd just issue a PR for it in case it was forgotten about!

Add robots.txt to block search engines

---

pluginHandler.js

Looks like PR #1337 caused an error in the refresh javascript when adding/removing plugins. This fixes that change while keeping the minification fixes.

Fix plugin refresh failure due to PR #1337

---

meshctrl.js

This pull request fixes a typo in the output of meshctrl.js's `--help` flag. The command for listing online users is `ListUserSessions`, not `ListUsersSessions`.

Fix incorrect command in meshctrl.js's --help output

---

meshctrl.js

**Error text:** Before
```
whalehub@pdh:~# meshctrl deviceinfo
Missing device id, use --id [deviceid]
```
**Error text:** After
```
whalehub@pdh:~# meshctrl deviceinfo
Missing device id, use --id '[deviceid]'
```
#
**Help text:** Before
```
whalehub@pdh:~# meshctrl help deviceinfo
Display information about a device, Example usages:
MeshCtrl DeviceInfo --id deviceid
MeshCtrl DeviceInfo --id deviceid --json
Required arguments:
--id [deviceid]        - The device identifier.
Optional arguments:
--raw                  - Output raw data in JSON format.
--json                 - Give results in JSON format.
```
**Help text:** After
```
whalehub@pdh:~# meshctrl help deviceinfo
Display information about a device, Example usages:
MeshCtrl DeviceInfo --id 'deviceid'
MeshCtrl DeviceInfo --id …
```

Update the error text and "help" output for all commands which use a device or group ID

---

redirserver.js

The CheckListenPort() function of redirserver.js was not using the optional bind address ("redirPortBind" in config.json), causing it to change the port number when unable to bind on all interfaces. Correct this by passing in 'addr' as the second parameter to createServer.listen().

Use bind address (if present) when checking redir port

---

views/default.handlebars

This small patch fix broken view on AMT only device. On AMT only device (CIRA or Direct) node.agent property does not exists thus it will throws exception which in turn break view rendering.

Add check node.agent!=null to fix AMT only broken view.

---

views/default.handlebars

Currently the node.intelamt metadata collected by MeshAgent contain ver, sku and other attributes. HW Connect buttons' visibility is currently determined by those attributes. However, node.intelamt metadata for AMT only device group does not have that attributes. This prevents the button which rightfully should be visible to be invisible for the device. This patch relaxes checking on AMT only devices and maintains existing checking for MeshAgent-managed device group.

Relaxing check for HW Connect button for AMT only device group.

---

meshcentral-config-schema.json

The current URL points to a 404 page. This pull request fixes that issue.

meshcentral-config-schema.json: Fix schema URL

---

views/default-mobile.handlebars
views/default.handlebars

Prior to this fix, the MeshCentral page would automatically reload itself after 10 seconds even if MeshCentral is still down when behind a reverse proxy like NGINX.

Prevent reverse proxy 5xx codes from triggering a page reload

---

agents/meshcmd.js

Minor update to fix poweroff NOT READY because of unsupported power off state.

Fix MeshCmd AMTPower poweroff action to use supported power state.

---

db.js

This change causes mongodump to dump to a null device when it runs `checkBackupCapability` as to not actually create a dump file. Mongodump does not have any builtin dry-run option for testing if the command will be successful.
- Tested for windows, linux, openbsd
As it stands, when meshcentral starts and checks for mongodump backup capabilities in `checkBackupCapability`, it does so by simply running mongodump.
When mongodump is run without the --archive flag, it simply dumps the entire mongodb database into the current working directory. Every time meshcentral starts, it dumps the entire mongodb into the backup directory, unzipped and without a password.
In my view, this defeats the purpose of being able to password protect the zip files. It also seems like an unwanted side-effect. …

mongodump to dev null for dry-run effect

---

db.js
meshcentral-config-schema.json

I have added mysql/mariadb database dumps to the automatic backups.
There are three main areas added:
1. Added a check for mysqldump to checkBackupCapability
2. Added db dump + archive for mysql and mariadb databases in performBackup
3. Added mysqldump path to config schema
I have tested MariaDB on linux and windows. MySQL has the same syntax.
<br>
<br>
PS:
The logic of performing db backups is very similar between MongoDB and MariaDB/MySQL. The overall structure is the same:
1. set up the dump command
2. run child process
3. perform archiving in callback function
If you want, I can refactor the db backups in a future commit (both mongodb and mariadb/mysql) since the only real difference is in setting up the dump command.

Add mariadb/mysql db dumps to autobackups

---

db.js

An invalid path name (or other similar errors) will cause meshcentral to crash and restart during an autobackup. This happens because `output` emits an ENOENT event. This is resolved by registering an error listener.
---
<pre><font color="#4CE64C"><b>noah_zalev@L460</b></font>:<font color="#295FCC"><b>~/Documents/meshc_testing</b></font>$ node node_modules/meshcentral/
WARNING: Unable to find mysqldump, MySQL/MariaDB database auto-backup will not be performed.
MeshCentral HTTP redirection server running on port 1024.
MeshCentral v0.8.7, LAN mode.
MeshCentral HTTPS server running on port 4430.
ERROR: Unable to perform MySQL/MariaDB backup: Error: spawn /bin/sh ENOENT
ERR: events.js:174
throw er; // Unhandled &apos;error&apos; event
^
Error: ENOENT: no such file or directory, open …

Register output error listener in autobackups

---

meshcentral.js

The permission bits must be expressed in octal.
Old behaviour
<pre>--w--wx--T 1 noah_z noah_z   99 Apr 19 12:55 <font color="#4CE64C"><b>log.txt</b></font></pre>
New behaviour
<pre>-rw-rw-r-- 1 noah_z noah_z   99 Apr 19 12:59 log.txt</pre>

Fixed log.txt permission bits

---

db.js
meshcentral-config-schema.json

I have added support for alternate db names for mysql/mariadb (#2535)
I have tested with both mariadb and mysql servers.
Fundamentally, this removes the database name from all queries - replaced with a `use database` query at the start of the connection establishment.
Additionally, I am creating an alternate connection object from the args passed in.  This is because if a user includes `"database"` in the configuration, and it is not yet created, the connection will fail. In order to keep the automatic database creation feature, a database paramater must not be passed in to `connectionPool()` / `createConnection()`. 
I have also simplified the automatic table creation by beginning with `create database if not exists`. Beginning with this was needed to support alternate db names, so its a …

Support different db names for MySQL/MariaDB

---

db.js

When I changed how a new database will be created in mysql/mariadb, I missed the final error condition which would call `setupFunctions()`. This will cause it to hang in the case that it doesn't have a database backend to work with. 
This also fixes the old behaviour, which was to start meshcentral _without a backend_, only for all data to be lost the next time it started.
The new behaviour is the same as what will happen with mongodb, which is to print an error and exit.
----
Mongodb
<pre><font color="#4CE64C"><b>noah_zalev@L460</b></font>:<font color="#295FCC"><b>~/Documents/meshc_testing</b></font>$ node node_modules/meshcentral/
Unable to connect to database: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27018
</pre>
New mysql/mariadb
Example error 1
<pre><font …

Bail if unable to connect to db

---

db.js

Step 1 in adding good mariadb/mysql ssl support
this cleans up creating the connection object used by the mariadb and mysql connectors
This is enough to use trusted ca signed certificates.
I will be able to finish the rest (support for self-signed certs) by this weekend for sure, I think.

Improved connectionObject creation

---

db.js
meshcentral-config-schema.json

Part 2 of mysql/mariadb connector SSL support
This adds support for using self-signed certificates at the database server. The needed CA certificate can be loaded off disk via the `caCertPath` ssl option (added to config schema). Currently, this uses an absolute path.
This also adds support for two-way ssl authentication, by giving the option to load a client certificate + key off the disk as well.

Added selfsigned cert support to mysql/mariadb ssl

---

db.js
meshcentral-config-schema.json

Added last needed options to mysqldump to support 2-way authentication
Added `dontCheckServerIdentity` option to disable hostname checking during certificate verification. Useful for self-signed certs where the hostname on the cert may not match.

Mysql/mariadb ssl support - additional options

---

meshcentral.js

PR just renames local function from `getCurrentVerion` to `getCurrentVersion` for consistency

refactor: rename function getCurrentVerion => getCurrentVersion

---

views/default.handlebars

I have added a Collapse All / Expand All button to the top toolbar. This was requested in #2593.
I'm not sure how you feel about UI code changes. This does not change `default-mobile.handlebars`, or the minified versions. If other changes are required to accompany this, just let me know.
---
The button functionality/text will change from collapose to expand (or vice versa) when the user clicks it, right clicks the expand/collapse image and uses collapse all/expand all, or manually expands or collapses the last group.

Added collapse/expand all button

---

db.js

Deleting a device group while using MySQL/MariaDB causes Meshcentral to crash. This bug goes back to the original implementation - surprised it hasn't come up before.
The callback function used in `CreateDB` gets passed around throughout db.js, until it is eventually re-called in `RemoveMeshDocuments`.
This results in the hilariously useless stack trace:
<pre>SQLERR1 TypeError: Cannot read property &apos;SetupDatabase&apos; of null
at /home/noah_zalev/Documents/meshc_testing/node_modules/meshcentral/meshcentral.js:717:24
at /home/noah_zalev/Documents/meshc_testing/node_modules/meshcentral/db.js:898:45
at process._tickCallback (internal/process/next_tick.js:68:7)
</pre>
It was very hard to find, but the fix is very simple :).

Bugfix: MySQL/MariaDB crash when deleting groups

---

meshuser.js

Part 1 of 2 (#2704)
This allows the `serverupdate` console command to accept a version argument.
Since distribution tags are valid for the install command, `npm install meshcentral@stable` and `npm install meshcentral@latest` both work out of the box. Therefore, "stable" and "latest" are supported arguments.
----
Coming in part 2:
I am currently working on validating the version argument. If an invalid version argument is given, it will make its way to `npm install meshcentral@version`, and the install will fail. This isn't harmful, but it causes the server to restart without updating to a new version, which is unideal.

Add version arg to selfupdate console cmd

---

meshcentral.js
meshuser.js

Part 2 of 2 (#2704)
This update adds version name/number validation to the serverupdate console command. This prevents the server from restarting itself uselessly in the case that an invalid version argument is given.
The list of version numbers is retreived via the command `npm view meshcentral versions --json`. Because there are more than 1400 versions, running this command is relatively slow, so I avoid using it unless 1) an argument is given and 2) the argument is not "stable" or "latest" which do not need to be validated.

Added version validation to serverupdate

---

amt/amt-redir-mesh.js

The file uses `use strict`. Use of the undeclared `i` causes a reference error. This should fix #2763 (if there are no other issues)

Fix undeclared variable (#2763)

---

meshcentral-config-schema.json

- schema shows option "ShowLog" when option in code is `errorlog`
- removes trailing comma

Fix myserver errorlog, fix trailling comma

---

views/default.handlebars

This removes trailing commas after interface names under Device details in the UI.
Before:
After:

Remove trailing commas from interface titles

---

meshcentral.js

Sometimes, we don't want the path to the config file to be interpreted as relative to the data path.

Allow passing absolute path to configfile

---

views/default.handlebars

Minor (incomplete) resolution for #2929
Both user events and general events have queries which exist without limits, so it is just a matter of adding an option in the dropdowns where `limit` is null.
This at least allows users to view all the events in the UI, though I agree more needs to be added. I can look at adding filters soon.

Add no limit option to events,userevents dropdowns

---

meshuser.js
views/default.handlebars

I have finally added the Last Seen column to the device list view.
The main problem in adding a last seen column was that not all the `lastconnect` data was loaded. However, agents which connect/disconnect do update `node.lastconnect`. I am loading all the last seen data for a user's nodes on page load, and only once. When agents connect/disconnect, they already update the info on their own.
On the server side, the last seen command gets a user's nodes and creates an associative array using the node IDs. Then all `lastconnect` docs are pulled from the db, `lcnode//` is converted to `node//`, and the last connect time is inserted only if the ID already exists in the associative array. This avoids leaking any information about nodes the user does not have access to. This is effectively …

Added Last Seen column to device view

---

db.js

The SQL query for `getPowerTimeline` was ordering in desc. This causes the newest times to appear first (think in terms of epoch timestamp being higher).
Now, when 'powertimeline' in meshuser calculates deltas, it creates a negative delta because the initial `time` is greater than the last `doc.time`.
```javascript
timeline.push((doc.time - time) / 1000, doc.power);
```
The result:
Obviously, this breaks the power timeline.
fix: don't order in desc.

Bugfix - correct power timeline query

---

views/default.handlebars

This is an updated fix for #2956 
The hard-coded colspan affects more than just the the default view. Other sort views (power, tag, group-tag,..) also have statically set colspans.
This sets the colspan to be exactly the correct size, and works properly when changing the number of columns or changing the sort.

Dynamically size device headers colspan

---

translate/readme.txt

The translate link will fail to download on some browsers due to Mixed Content (HTTP request from HTTPS connection)
#2970

Update translate link to https

---

views/default.handlebars

I think this is a fairly niche feature, but useful for users who have a very large number of deployed agents.
It is useful to find agents which have been disconnected for a long time: they may have been decomissioned and need to be removed, the agent may not be connecting and needs to be reinstalled, etc.
Up until the Last Seen column, it has been too tedious to go through disconnected agents and find how long they have been disconnected. However, when there are a very large number of agents, it can still be difficult to go through the list even with the last seen column.
Being able to sort by Last Seen solves this problem.
---
If the last seen column is not selected, sorting by last seen will automatically select it:
If the lastconnect data has not been fetched yet, it will be fetched …

Added Last Seen sort option

---

amtprovisioningserver.js
certoperations.js
common.js
meshcentral.js
webserver.js

Essentially the same as #2928, but extended to all places I was able to find where `path.join` was used indiscriminately and the right-hand side of the join was a variable; in addition, I added a function to `common.js` to factor the common logic out into one place, and replaced some handwritten absolute-path checks as well.
:warning: This is running with no issues on my meshcentral deployment, but I have not tested all the functionality I touched, so a careful review would be appreciated.

Handle all configurable paths as potentially absolute

---

agents/meshcore.js

Fix capitalization uuid to UUID to make console apf command working again. Invalid capitalization caused UUID undefined and APF cannot be performed. Current work around was to eval "meshCoreObj.intelamt.uuid=meshCoreObj.intelamt.UUID" to ensure the undefined reference to uuid is created.

Fix capitalization uuid to UUID to make console apf working

---

meshcentral.js

Fixes #3068 
Issue in whatwg-url affects mongodb >= 4.1.1

Cap mongodb at 4.1.0 in response to whatwg-url err

---

webserver.js

I noticed when looking at #3083 that the agent-only web handler had deviated from the regular one. If using a reverse proxy, in order to set the client IP address, `tlsoffload` needs to be set to an IP and can not be set to true like in the standard request handler.

Update setting cleint ip in agentonly webrequest

---

views/default.handlebars

This is a fix for #3231
When attempting to search a node's files, the variable `winAgent` was written as `winagent`.

Fixed reference error in file search (fix for #3231)

---

meshuser.js

Fix obscure bug when the last user added in list of addusertousergroup was an unknown user causing the server to crash.
Also updated the group update message of same to display all users added, rather than only the last one in the list.

Fix bug in addusertousergroup

---

db.js
meshcentral-config-schema.json

Adds a command line option to MariaDB mysqldump to resolve LOCK TABLE permission issues on AWS RDS.
I have updated the config schema
For #3283

Added awsrds config option

---

webserver.js

For power events, when the dates/times are pulled from MySQL/MariaDB, they get pulled as strings instead of Date objects.
This causes the power events csv generation to fail, as a string has no function `getTime()`. 
I have added a check to see if time pulled from the database is a string, and if so, to convert it to a Date object.

Fix MariaDB/MySQL power events

---

meshuser.js

With MariaDB/MySQL, event reports are not properly filtering events. As a result, you get rows containing only a timestamp, corresponding to events it was not meant to report on (such as login actions):
This fixes the message id filtering for MariaDB/MySQL (and I assume postgres, which I saw you just recently added).
---
The issue lies in the lines
`
if ((docs[i].msgid != 5) && (docs[i].msgid != 10) && (docs[i].msgid != 11) && (docs[i].msgid != 12) && ((docs[i].msgid < 122) && (docs[i].msgid > 126))) continue;
`
Particularly `((docs[i].msgid < 122) && (docs[i].msgid > 126))`. Since an integer can't be both less than 122 and greater than 126, this condition can never evaluate to true, and no events are filtered as a result.
Rather than fixing the condition, I think it is all around cleaner …

Fixed report msgid filter

---

meshcentral.js

When resetting an account form the command line, the password is passed in raw from the cli, which allows JS to decide the type. JS is not guaranteed to choose the type correctly.
For numeric passwords, JS will pass this in as an Integer, and the server will crash if using MongoDB or throw an exception for MariaDB/MySQL.

Bugfix - ensure resetaccount pass is string

---

meshagent.js

This updates the agent IP on reconnect. As it currently stands, when an agent connects, the IP address is only updated if the agent is initally starting and sends its core.
If an agent reconnects without restarting (suppose it moves from a mobile hotspit to a WiFi connection), nothing will have changed in the core, so it will not resend it. However, the device IP is only set from `ChangeAgentCoreInfo()`. As a result, `node.ip` ends up having an incorrect result in the database when a device changes networks.
#3354

Update agent ip on device reconnect - fix #3354

---

meshagent.js

After calling `MeshAgent.close()` with `arg = 2` (hard disconnect), the following will be called: `ws._socket._parent.end()`.
However, ws._socket._parent can be null. Hence, the following error is produced:
```
TypeError: Cannot read property 'end' of null
at Object.obj.close (/home/noah/wrk/meshc_testing/node_modules/meshcentral/meshagent.js:60:50)
at Object.obj.forceMeshAgentDisconnect (/home/noah/wrk/meshc_testing/node_modules/meshcentral/webserver.js:6872:131)
at /home/noah/wrk/meshc_testing/node_modules/meshcentral/meshuser.js:5702:20
at /home/noah/wrk/meshc_testing/node_modules/meshcentral/webserver.js:7076:47
at /home/noah/wrk/meshc_testing/node_modules/meshcentral/db.js:1318:246
at /home/noah/wrk/meshc_testing/node_modules/meshcentral/db.js:1055:45
at process._tickCallback …
```

Fix null reference on agent disconnect

---

webserver.js

The agent key was not checked if using `agentPort`.
This includes the check for agent keys if using an agent port.

Include agentKey check at agent only port

---

translate/translate.json

Wrong translation make search for tag in German impossible by word "tag".
You had to write "Etikett:" which means "Label".

Fix for #3486

---

agents/meshinstall-linux.js

When the environment process does not have a language set, it defaults to "C". This PR changes the language to English and sends a console log about how to find and specify the language for translation.
Without this, the it will set the language to lowercase "C" which is not found in agent-translations.json, which throws an error on install "Language: c is not translated" and exits.

 added fix to hande process.env.LANG = "C" 

---

docker/Dockerfile

this simply allows for logs to be in the correct timezone instead of UTC
can be set in docker using `TZ=Europe/London` for an environment variable

add timezone support to docker

---

views/agentinvite.handlebars

Some users still habe issues to see, that small text is a link for agent Download and try to click on the Preview-Image.
The idea is, to start the Agent-Download when clicking on the preview Image. So that at least they get the agent downloaded.

Make Agent-Images also clickable for agent download.

---

docs/Example configs/haproxy-with-sni-sample.cfg

mini explanation on when to use trustedProxy instead of tlsOffload

HAProxy split trustedProxy into secondary section

---

webserver.js

Fixes #4493 
The passport-openidconnect module adds 'openid' to the beginning of the scope (as it is required), I removed it from the request as well as the unused 'groups' scope.

Updated OIDC Scope

---

meshcentral.js

This pull would allow the debugger to be activated from the configuration file in the same ways it is activated by arguments currently.

Feature: Allow for debug options in config file.

---

webserver.js

Fix checking if group sync is enabled before checking if the parent property exists.
This was already fixed when creating new users so I copied the solution over to the existing user section to match.
Fixes #4520
Fixes #4517

BUG: Fix handleStrategyLogin checking undefined property.

---

apprelays.js

when trying to web relay [cockpit](https://cockpit-project.org/) it fails to connect to the websocket 
because cockpit requires looking at the origin header which is missing because its not relayed
```
Sep 17 11:48:19 maycocksserver cockpit-ws[44754]: received request without Origin
Sep 17 11:48:19 maycocksserver cockpit-ws[44754]: Received invalid handshake request from the client
```
example for apache below
https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt#set-up-apache-reverse-proxy-in-a-subdomain

allow origin header to be relayed

---

meshctrl.js

Greetings, @Ylianst!
While doing another automation with MeshCentral, I discovered that meshctrl does not know how to create "Local devices, without agents" groups. Adding such an opportunity was not so difficult. I checked locally that the group is created with the correct mesh type.
Please accept the pull request.

Add support create agentless gpoups in meshctrl.js

---

db.js

Hi @Ylianst I've taken the liberty to improve the AceBase implementation in MeshCentral. I have not tested the changes yet, will do so asap.
I have also taken a look at why you were seeing slow performance on your `remove` queries, I will be releasing a new version of AceBase tomorrow that will drastically improve this. Will keep you updated on this.
If there are other issues you would want to bring to my attention, please do so. I'm happy to help.

Improve AceBase support

---

webserver.js

When setting up SAML with AD FS, we ran into the problem that only the First Name and Last Name end up in the username. We are fans of using the full name, including the Patronymic, which we prescribe in the full name. Therefore, it became necessary to correct the code so that it was possible to use the user's DisplayName as an alternative field for obtaining data.

Added displayname handling to SAML strategy

---

amtscanner.js

fix of bug that crashes the meshcentral when there is only digits and one comma on the version of the amt

fix of amt bug

---

docker/Dockerfile

#4737 #4742 
Since the initial solution of simply building the existing Dockerfile with the multiplatform option failed, timing out on the translation step, I'm trying to adjust the Dockerfile
- step 1: the "builder" runs on the platform's native architecture, whatever it may be, and does minification and translation. Only runs once even though we may be building for multiple platforms.
- step 2: what will be the final image runs on the target platform (arm64 and amd64) and simply copies the minified, translated files.
I chose to use the node docker image at least for the builder step, in order to not have to install nodejs and npm twice.
Once again, I haven't been able to test a full release with Github actions (I'm learning to do it but it's going to take a bit).
I've tested building …

[FIX][IMP]adjust dockerfile to support multiplatform build

---

amt/amt-wsman-comm.js
interceptor.js
views/default-mobile.handlebars
views/default.handlebars
webserver.js

This is to address #4760 and #4765
Newer NodeJS reject unsafe legacy negotiation. Additional flag is added to mitigate that issue. This applies to webrelay TLS socket and also on amt-wsman-comm.js
These patches ensures TLS connection is used when Direct TLS is possible. Non-TLS may be disabled.
There is an issue on NC length on interceptor.js. It is now 8 bytes long.

Fixes on AMT KVM for newer AMT firmware and newer Node JS TLS compatibility fix

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
docker/config.json.template
sample-config-advanced.json
sample-config.json

Existing config.json schema url does not work. Also does not match the `id` in the schema file. This commit corrects the url. vscode and similar editors now work well after the correction with verification and autocomplete.
Cheers

Correct config.json schema URL to match github schema location

---

webserver.js

I am very sorry! My last pull request https://github.com/Ylianst/MeshCentral/pull/4943 (merged yesterday) was flawed and lead to a critical error when starting MeshCentral.
```
ERR: /root/node_modules/meshcentral/webserver.js:6344
if (parent.parent.pluginHandler != null) {
^
TypeError: Cannot read properties of undefined (reading 'pluginHandler')
```
The problem was the property access of `parent.parent`, when it just has to be `parent`.
This PR fixes this problem. Again, many apologies and thanks for merging the new hook!
**Edit:** You can also revert the first commit (if you want to) and I will make a new PR with the correct changes.

Fix pluginHandler access

---

docs/docs/meshctrl/index.md
meshctrl.js

The only format that makes sense to me is CSV, node and mesh ids in the sessions report are just too big for terminal view and JSON is inefficient (too much white-space).
The first field (group) derives from the groupby argument and is "0" when no grouping is applicable (e.g. db reports).
resolves #3472, resolves #3509

add reports to meshctrl

---

.github/workflows/codeql-analysis.yml

https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

update codeql to v2

---

webserver.js

Noticed I had the same issue described here [4545](https://github.com/Ylianst/MeshCentral/issues/4545#issue-1369905128). But my OIDC provider doesn't support discovery. This should fix it. 
@Ylianst @mstrhakr

add oidc options from config if they exist

---

public/styles/style.css
views/default.handlebars

Reference Issues/PRs
None
what does this implement fix? Explain your changes. 
Group together some CSS code into one class to reduce code redundancy
any other comments.
I'm working on a new UI for my own instance of MeshCentral and I noticed some changes that could be made.

Remove code redundancy

---

webserver.js

https://github.com/Ylianst/MeshCentral/issues/4870
If user has 2FA enabled and tries to login with URL parameters authentification method, then the login should fail.

Fix basic URL user/pass auth to fail if user has 2FA

---

certoperations.js

SHA2 or above hashing algorithms are now used to generate provisioning cert but MEBx only supports adding SHA1 hashes.
https://github.com/Ylianst/MeshCentral/blob/master/certoperations.js#L112 I think signer should use the same hashAlgo that was used to generate the provisioning cert. 
This should fix the activation to ACM issue if a customer adds a SHA1 hash of provisioning certificate via MEBx

fix: activation to acm issue

---

meshcentral.js

existing people will need to`npm uninstall webdav` from inside the `meshcentral` folder in `node_modules`
and then let it install the pinned version

pin webdav to version 4

---

db.js
meshcentral.js

Fix webdav upload

---

meshrelay.js

60 seconds is just way too long for meshcentral to connect to both devices for relaying, so we set this to 15 seconds instead

update timeout from 60sec to 15sec

---

meshcentral.js
package.json

Fixes #5300
for some reason NPM is installing new versions of packages on some devices?
left value is installed, right value what is asked for
```
ws string 5.2.3 string 5.2.3
cbor string 5.2.0 string 5.2.0
archiver string 5.3.2 string 5.3.1
express-ws string 4.0.0 string 4.0.0
cookie-session string 2.0.0 string 2.0.0
ua-parser-js string 1.0.35 string 1.0.35
node-windows string 0.1.14 string 0.1.4
otplib string 10.2.3 string 10.2.3
```
so just update the packages anyways

update node-windows and archiver to latest version

---

readme.md

Fixed outdated doc link to https://meshcentral.com/info/docs

Fix: readme doc link issue

---

meshmessaging.js

Fixes #5207
`'0'`, or a 4-digit stringified number if they're using the legacy username system

fix discord hash compare

---

certoperations.js

The r.certs[0].md field is null. Therefore, attempting to check if r.certs[0].md.algorithm is null will result in an error.

fix skip-amt-algorithm

---

agents/modules_meshcore/win-info.js

Was only showing Windows defender OR None, now shows multiple correctly

fix multiple av detection

---

agents/meshcore.js
meshagent.js
meshuser.js
views/default-mobile.handlebars
views/default.handlebars

Add Volumes+Bitlocker

---

agents/meshcore.js

If 'privacy bar' user consent option is enabled for desktop access, then it will show the privacy bar in user side while taking the desktop access. But it will not disconnect the session even though the end user clicks the close option. 
It will only close the privacy bar. This will solve the below issues.
Fixes #5289 
Fixes #5315 
Fixes #5216

Disconnect desktop session from User-side using Privacy bar.

---

db.js
meshcentral.js

use mysql2 package instead to support mysql8

---

docker/startup.sh

Allows ARGS variable in .env file to be used when REVERSE_PROXY != "false"

Allow $ARGS in $REVERSE_PROXY .env docker

---

views/default.handlebars

Fix a typo in the file-size dropdown menu on the "Files" page. "Human Readble" should say "Human Readable".

Fix typo in Files view (readble -> readable)

---

meshuser.js

fix linux csv output

---

meshcentral-config-schema.json
views/login2.handlebars
webserver.js

add language selector to login

---

views/default-mobile.handlebars
views/default.handlebars

Fixes #2460
Fixes #83
Fixes #3409
shows the Windows status of the drives if it has that information now

add basic windows drive status

---

docker/Dockerfile
mcrec.js
meshcentral.js
translate/translate.js

Align and specify NPM module versions
The Dockerfile specifies NPM modules to be installed.  However, some do not specify a version, so the latest is installed.  Later in meshcentral.js mainStart() specific versions are required.  If they don't match the latest version, all modules will be reinstalled to get the specific versions.
#5684 Soft version conflict on NPM modules causes NPM modules to be installed on startup in Docker
#5545 Docker on Debian 11 fails on version 1.1.15 and 1.1.16 giving NPM errors
#5681 InstallModules() installs all modules, not just missing modules (regression)

Interim fix for NPM module version mismatches

---

views/default-mobile.handlebars

The terminal mode was not usable on many Android phones because the soft keyboard had no enter key. IPhones seem to have the default imput mode "text". For Android I added the attribute imputmode="text" and got also the enter key on the soft keyboard.

fix mobile terminal not showing enter key for Android soft keyboard

---

views/default-mobile.handlebars
views/sharing-mobile.handlebars

I found the same line as in pull request #5686 in sharing-mobile.handlebars and also changed it to make the fix complete.
Thank's for merging.

fix mobile terminal not showing enter key for Android soft keyboard for sharing-moblile.handlebars

---

meshctrl.js

add groupmessage/grouptoast to meshctrl

---

amtmanager.js
amtprovisioningserver.js
views/default.handlebars

- added full version of 3 markings, for easier comparison
- added marking in amt only groups to detect the state of the amt

update full version, and marking of the amt to check if activated

---

views/default.handlebars

disconnect sessions first before logout on idletimeout

---

pluginHandler.js

On file systems that support this, the executable rights of a plug-in's files are retained.

Preservation of the executable rights of the files contained in a plugin

---

agents/meshcore.js
translate/translate.json
views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/5984

open files/folders on desktop with files and console with openfile

---

webserver.js

add nice404 to invite page and fix invite with dns use

add nice404 to invite and fix invite with dns use

---

docs/docs/install/install2.md

Updated install document - Corrected chmod command examples. -R recursive options needs to be before permission value.

Updated install document - Corrected chmod command examples.

---

agents/meshcore.js

Fixes https://github.com/Ylianst/MeshCentral/issues/4791
Fixes https://github.com/Ylianst/MeshCentral/issues/5845

allow msh get/set/delete from console

---

letsencrypt.js
meshcentral-config-schema.json
sample-config-advanced.json

Fixes https://github.com/Ylianst/MeshCentral/discussions/6057

add zerossl acme

---

translate/translate.json
views/default-mobile.handlebars
views/default.handlebars
webserver.js

add encoding options to remote desktop

---

webserver.js

I have been experiencing a bug with file downloads on agents because of IP restrictions set with userAllowedIP. My investigation is detailed in my comments to #4078.
After making this change locally, this problem has been resolved for me. I'm no longer receiving 401s on file downloads.

Check agent IP address instead of user IP address for agent file downloads

---

meshcentral.js

This adds the ability to use environment variables in place of command line args.
It parses each environment variable starting with "meshcentral_" (normalized) and sets the command line argument after that to the value given. For example:
`MESHCENTRAL_CONFIGKEY="AOEUAOEUAOEU" node ./meshcentral`
Is effectively the same as:
`node ./meshcentral --configkey "AOEUAOEUAOEU"`
It is validated against validArguments and ignores anything that is not set there. Command line arguments also take precedence over environment variables. It shares a precedence with command line variables in regards to overriding config file options.
The motivation for this is for use in scalable cloud environments where it is undesirable to provision the system drive with particular secrets. Currently this can be handled …

Added ability to use environment variables as arguments

---

apprelays.js

Add `.trim()` to the header label value (`i`) to fix a rare circumstance where there can be a space in a header name.
See Issue #6305

Update apprelays.js to fix Header issue

---

amtmanager.js
meshuser.js
views/default.handlebars

Hello !
This PR fixes Intel AMT: One Click Recovery that is currently unusable due to an impossible condition. It also replace .iso (which is an unsupported format) to .efi to allow BIOS to load the file
You may need to squash commits included in this PR to keep it clean
It has been tested on a Dell Optiplex 7400 AIO (Intel AMT v16) and with iPXE(.efi) that can be found here: http://boot.ipxe.org/ipxe.efi
Interestingly enough, I came across Intel EMA code that do something similar, and there is a bug in its implementation of makeUefiBootParam() where the len argument is ignored, in the case of a number it'll always be 4 bytes. I'm asking myself if this difference would be volontary and better compatibility with more BIOS software
Feel free to ask any questions or modifications 👐

AMT: Fix One Click Recovery support

---

agents/meshcore.js

There was a bug when an agent was unexpectedly disconnected from the server that it would not update the mesh core object with the server. In the worst case, this would make the server think that the agent doesn't have any terminal/file/desktop capabilities, and would require either an agent restart or a core replacement to fix.
This fix just clears the "last updated" cache the agent uses when the agent connects, instead of only on agent instantiation, which solves this problem, since there is a forced update during that time anyway.

Fixed bug with agent reconnecting

---

views/login-mobile.handlebars
views/login.handlebars
views/login2.handlebars

This commit removes our login validation and use the built-in one.
Fix #6428

Use built-in login validation

---

webserver.js

In some cases, a client could send packets that would cause the webserver to error and crash. In my case, I was getting the error:
```
RangeError: Invalid WebSocket frame: MASK must be set
at Receiver.getInfo (meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:284:16)
at Receiver.startLoop (meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:131:22)
at Receiver._write (meshcentral/node_modules/express-ws/node_modules/ws/lib/receiver.js:78:10)
at writeOrBuffer (node:internal/streams/writable:570:12)
at _write (node:internal/streams/writable:499:10)
at Writable.write (node:internal/streams/writable:508:10)
at TLSSocket.socketOnData (meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:1164:35)
at TLSSocket.emit (node:events:519:28)
at …
```

Added global ws error handler

---

db.js
meshcentral-config-schema.json
meshcentral.js
meshuser.js

If autobackup wasn't defined in the config and an autobackup was triggered from the serverconsole, the backup would fail because of uninitialized properties.
Removed some extraneous remarks in those parts.
Set default zip level to 5 as level 9 does not make the backup that much smaller at much more performancecost, especially on smaller hardware and large backups. > going to make the ziplevel a config option

Fix autobackup defaults and zip level for performance

---

db.js
meshcentral-config-schema.json

Add maintenance and performance options to the sqlite part.
Defaults are based on the the default of sqlite with the addition of an incremental autovacuum.
Database filename can also be done in the object with the 'name' property, so the 'string' type could be removed from the 'sqlite3' property to stay in line with the rest.

Add sqlite config options

---

authenticode.js

Some enterprise environments mandate that all communication happens through SSL. This merely enables the user to set their time server to an HTTPS site, e.g. `"agenttimestampserver": "https://timestamp.sectigo.com/authenticode"`.

Added the ability to fetch timestamp for codesigning through https

---

meshuser.js

I stumbled across this issue when trying to remove a user from a mesh using meshctrl `removeuserfromdevicegroup`. I was attempting to remove `user1` from a mesh and received `Invalid userid`. After adjusting the Id to `user//user1`, the command would proceed without issue. At first I just figured the function required the full Id with the prefix, but thought that odd as `addusertodevicegroup` distinctly does NOT accept the prefix. 
After looking at the code, the function requires a minimum of 8 characters for the user Id. This causes issues when using meshctrl with Ids under 8 characters. This will also cause an issue in the web UI for Ids of only 1 character. User `user//a` does not satisfy the length requirement and cannot be removed from a mesh in the web UI.

adjust removemeshuser to allow for shorter user ids

---

db.js

#6417
Identified the issue with anomalous mesh and user group objects in a peering environment. The `dbMeshChange` and `dbUgrpChange` were modifying the original variable when making adjustments for the DispatchEvents functions. This was also modifying the object in memory.
I've adjusted the function to create a copy of the object for adjustment rather than modifying the original variable.

fix adding meshes and user groups in a peering environment

---

db.js
meshcentral.js

Found these when switching to self-signed ssl certs on mariadb & mysql.
Fix:
error 2026: "TLS/SSL error: Server certificate validation failed. The certificate's CN name does not match the passed value. Error 0x800B010F(CERT_E_CN_NO_MATCH)"
by adding '--ssl-verify-server-cert=false'
And deprecated warnings by updating the modules.

Mariadb/mysql: Fix ssl on autobackup cmdline and deprecated warnings

---

db.js

See: https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted
The function to create a string of an array puts double quotes around the literals used in the sql statements. This is tolerated as explained in the article, but should be corrected to single quotes.
This is only used in the sqlite functions.
It generates a log warning for now, but maybe an error in the future.

Fix quoting of string literals from double to single

---

docs/docs/install/install2.md

feat: Added Elestio as one-click deploy option

---

db.js

fixes using default databasename 'meshcentral' if not configured in config.json

connectinArgs.Database > connectinArgs.database typo

---

agents/modules_meshcore/computer-identifiers.js

Fixes #6582 
The drive parameter needs a ':' added as the var only has the driveletter.

fix bitlocker/manage-bde cmdline

---

meshcentral-config-schema.json
meshcentral.js

This would resolve issue #6644 by restoring the behaviour of autobackups running by default.

Re-enable autobackups by default (#6644)

---

views/default-mobile.handlebars
views/default.handlebars
views/default3.handlebars

#3894 
similar to this commit only with ip of device
`https://meshcentral/?viewmode=10&gotodeviceip=10.1.1.1`

Added support for &gotodeviceip=x.x.x.x

---

db.js
meshcentral-config-schema.json
meshcentral.js

Added an option to configure the hour during which the autobackup should be done instead of being determined by the service start time to have more control if wanted.
There is also the extra logging for #6675. I tried to replicate the issue, but it worked every time, on windows and linux.
Hopefully the extra logging will help to determine the issue.
Debug logging for the backup was under the 'db' category, moved it to the 'backup' debug category to keep it clean.
Add "debug": "backup" to the config.json for extra logging besides the default start and file removal logging of the autobackup.

Autobackup update

---

webserver.js

added relaystate and regex check to prevent redirecting to a page outside of the configured server. also checks for the allowed query params
ref #6272

Update webserver.js - allow saml relaystate in POST request

---

views/default3.handlebars

The password validation function for Intel AMT passwords enforces a maximum password length, but there's nothing in the UI to tell the user this or to indicate that a provided password is, specifically, too long.
This adds the maximum length to the UI.

Note maximum password length in USB key dialog

---

meshcentral-config-schema.json
meshuser.js
sample-config-advanced.json
views/default-mobile.handlebars
views/default.handlebars
views/default3.handlebars
views/sharing-mobile.handlebars

Closes #6772 
This merge request adds a new config parameter called `logoutOnIdleSessionTimeout` (boolean) to configure whether you want to logout after `userSessionIdleTimeout` or just disconnect any remote desktops, terminals and files.

Add support for logoutOnIdleSessionTimeout

---

webserver.js

If a (new) user has no webstate saved yet the app crashes at login. This is because in #6763 the `var webstateJSON = JSON.parse(webstate);` stumbles if webstate is en empty string. By making the webstate default '{}' instead of '' this is fixed.

Fix: Init webstate with empty 'object' instead of empty string

---

meshctrl.js

Tag filtering wasn't working because, instead of pushing the node that matches the search, its index was pushed.

fix meshctrl tag filter search

---

common.js

Check https://github.com/seald/nedb/tree/master?tab=readme-ov-file#inserting-documents
"," also isn't permitted in the field name, added it to the un/escape function

Add comma to escapeFieldName for NeDB

---

agents/meshcore.js

I guess, the parameter should be named "id" not "index" .
```
> agentmsg
Proper usage:
agentmsg add "[message]" [iconIndex]
agentmsg remove [id]
agentmsg list
> agentmsg add "Hello world!"
Agent message: 000002F0396D43A8 added.
> agentmsg add "Howdy?"
Agent message: 000002F0396D4BA8 added.
> agentmsg list
[
{
"msg": "Hello world!",
"icon": 0,
"id": "000002F0396D43A8"
},
{
"msg": "Howdy?",
"icon": 0,
"id": "000002F0396D4BA8"
}
]
```

Fix parameter names in usage message for the "agentmsg" console command

---

pluginHandler.js

while working on #6875 i realized that the temp file for downloading is not deleted when the request is redirected. This is not a big problem since it's a zero-byte file. anyway it doesn't look good.

[pluginHandler] delete temp file when download is redirected

---

db.js
meshcentral-config-schema.json

#6903 Add 'mongoDbDumpArgs' option to override the default behavior of autobackup, which is to use the parameter 'mongoDb' as the --uri argument to mongodump. When using restricted mongodb users, this errors mongodump.
It gives the flexibility to use different formatting for the connection (uri format) and mongodump (argument format).
Also made the error message more descriptive.
...and put the option in the autobackup category

Add mongodump args option

---

db.js

Fix for #6968 
In fs.unlink forgot to check `if (err)`

add forgotten err object check for fs.unlink

---

docs/docs/meshcentral/codesigning.md
meshcentral.js

This pull requests consists of changes to the codesigning.md file detailing the externalsignjob feature. 
In meshcentral.js, when calling to code sign the agent, mesh central provides a callback. 
This enhancement attaches the signingArguments to the callback function used for code signing. After MeshCentral has completed its update to the agent (such as setting values from domain, etc.) and signed the agent, callExternalSignJob is called. if externalsignjob is not set, it simply returns.  If it is set, it spawns the value in externalsignjob and passes the path to the file for the externalsignjob to process. 
This doesn't have to be used for code signing. For example, it could be used to calculate MD5s of the agent and posted to a website.
Public code signing now requires a hardware …

externalsignjob - External Code Signing Job

---

db.js
meshcentral.js

The currently used webdav package is v4 using an older axios dependency, giving a security warning in npm audit. The v5 version is an esm package, so converted the upload function accordingly. Now it's up to date again, also dependency-wise.

WebDAV: update to v5

---

db.js

Fixes #7301 
- Run user/pw/dbname through `encodeURIComponent` to allow for special characters (@ & = + $ etc) in the command line
- Add quotes to the create database statement to allow creating a db with special characters
- Remove dbname from dumpfilename to avoid filename errors because of special characters in the dbname

PG-allow special characters in user/pw/dbname
