Ylianst/MeshCentral

public/styles/style.css
views/default.handlebars

This should fix the problem with an empty page when device is selected

fixing invisible content and page height

---

public/styles/style.css
views/default.handlebars
views/login.handlebars

Reverts Ylianst/MeshCentral#193

Revert "Fixed reported CSS issues and added support for IE"

---

agents/meshcmd.js

Added provisioning to ACM flow and unconfiguring from ACM flows to MeshCMD.  Provisioning to ACM requires amt-rcs service

MeshCMD - Added provisioning to ACM flow and unconfiguring from ACM flows

---

apfserver.js
meshcentral.js
webserver.js

Ylian,
This is initial version of APF over Websocket support. I will send test script separately via email.

Inital commit for APF over secure websocket

---

agents/modules_meshcore/amt-scanner.js

Addressing issue #516. amt-scanner.js now supports scan callback function.  Additional fix on iprange scan to remove network and broadcast address to avoid irrecoverable UDP socket error.

Add callback support for amt-scanner scan function

---

meshcentral.js
mpsserver.js
mqttbroker.js
package.json
webserver.js

MQTT over MPS port and WSS. Test code will be sent via email. It can also be debugged with MQTT Exporer too http://mqtt-explorer.com/

Added MQTT support over WSS and multiplexed with MPS

---

agents/meshcore.js
agents/meshcore.min.js
meshagent.js

Update to enable plugins to engage with agents via the sendPeriodicServerUpdate call and participate in periodic data exchanges.

Expand PluginHandler to Support Periodic Updates

---

agents/meshcore.js
agents/meshcore.min.js
meshagent.js

Reverts Ylianst/MeshCentral#610

Revert "Expand PluginHandler to Support Periodic Updates"

---

meshagent.js

- Introduce plugin hook to verified agents with non-recovery cores
- Introduce plugin hook to agent message data, should the plugin need to interact (without any additional bandwidth used for installs without plugins enabled)

Expand Plugin Interactions

---

meshcentral.js
package.json

Did some clean up on the module install code. 
(Merging this PR will auto close #631)
(psst @Ylianst, I wouldn't mind you marking some issues as `good first issue` :+1: )

Clean up module install code

---

apfserver.js

Ylian,
This is to fix apfserver authentication issue. You fixed mpsserver.js for node migration to different device group.
Regards,
Joko

Update apfserver node search to fix authentication issue

---

pluginHandler.js
views/default.handlebars

Small update to remember a last plugin tab selected, if any, and jump back to it.

Remember the last plugin tab and jump back to it.

---

views/default.handlebars

- Clear plugin headers / pages on device change
- Safety check existence of plugin on device change
- Add plugin eventing capability

Safety checks, cleanup, and add eventing capability to plugins

---

agents/meshcore.js
agents/meshcore.min.js
public/scripts/amt-terminal-0.0.2.js
webserver.js

- (not terminal related) Fix "undefined" when downloading a backup
- Don't store automatic commands in the bash history
- Refactor terminal setup code
- Create interactive terminals without python (see #677) [;)](https://github.com/Ylianst/MeshCentral/pull/677#issuecomment-558259078)

Various (linux) terminal improvements

---

meshuser.js
pluginHandler.js
plugin_development.md
views/default.handlebars

Fix argument passing for internal pluginHandler calls.
Add two new hooks for plugin devs.

Additional hooks, better passing of arguments

---

plugin_development.md
views/default.handlebars

Allows plugins to take action on page changes

Add 2 new hooks for detecting page changes in the webUI

---

translate/translate.json

The latest tweak of the language file, includes the user group settings

Tweaked NL translation including latest additions (0.4.6-u)

---

translate/translate.json

translated the latest additions and corrected an typo

Tweaked dutch

---

translate/translate.json

- fixed pronoun due to resolved ambiguity

Updates German translation

---

meshcentral.js

* fix domain-based IP list handling for UserBlockedIP
* fix global IP list handling of comma-separated lists (#822)

Fix handling of IP address lists (#822)

---

translate/translate.json

Reverted translation of ID "DataChannel", corrected ambiguity of "SharedProcess" and corrected pure case of "Soft disconnect agent".

German translation update (#765, #793)

---

translate/translate.json

* Harmonised translation of "present", ref #765

Another German translation update (#765)

---

agents/meshcore.js
views/xterm.handlebars

(Feel free to push to this branch btw.)
Basically just sending the SIGWINCH signal and reacting to it in the shell. Ideally data would be sent along with the signal somehow so the shell can just resize without calculating the terminal size.
Why I marked this as WIP:
1. I didn't test this on anything other than script+bash
2. Resizing the window multiple times in a short time frame for multiple seconds causes the terminal to "lag out" temporarily, can be cancelled by pressing ctrl+c.
fixes #859

[WIP] Add dynamic resizing of xterm tty

---

agents/meshcore.js
views/xterm.handlebars

Reverts Ylianst/MeshCentral#868

Revert "[WIP] Add dynamic resizing of xterm tty"

---

agents/meshcore.js
public/scripts/amt-terminal-0.0.2.js
views/default.handlebars

Literally the same pull request because the other one got closed for [no reason](https://github.com/Ylianst/MeshCentral/pull/916#issuecomment-582647871)...

Fix issues with linux/macos terminal

---

translate/translate.json

Default strings added (FR, DE etc)

Update Dutch language 0.4.9-D

---

translate/translate.json

Restored some typo's (missing: , )

updated translation 0.4.9-E

---

translate/translate.json

dutch translation update 0.5.0-R

---

translate/translate.json

completed the strings, witch were over left to translate after cleanup the dots :-)

Dutch update 0.5.1-o

---

translate/translate.json

* all missing German translations added
* some existing German translations improved
* translation update performed using current RessourceTranslator, causing a re-sort of the translate.json file for language id

German Translation for MeshCentral #765

---

translate/translate.json

the second file, was an empty old translation, with no  "loc" data

2 dutch language update 0.5.56

---

package.json

Two-factor authentication is a great feature!

Adding 2FA to list of keywords

---

translate/translate.json

Cleaned up some empty translated strings (merged at new location)

Dutch language update 0.6.1

---

translate/translate.json

Dutch language update 0.6.46

---

agents/agentrecoverycore.js
agents/recoverycore.js
meshuser.js

Fixed "avaialble" to "available" in 3 user (admin?) facing areas.

Spelling fix

---

translate/translate.json

* corrected mistranslations introduced by automatic translation
* unification of some terms
* display optimizations

Updated German translation for MeshCentral

---

translate/translate.json

* fixed mistranslations introduced by automatic translation
* fixed out-of-context misinterpretations

Updated German translation

---

translate/translate.json

question: what are "file files" can't translate it because the meaning is unknown

Dutch language update 0.7.91

---

agents/meshcmd.js

This is to add AMTPower Boot to PXE, HDD and CD/DVD capabilities. This feature is only for poweron, powercycle and reset.

Add boot device selection to MeshCmd AMTPower [PXE, HDD, CD]

---

db.js

if dburl then use --uri option

Fix for #2486

---

meshcentral.js

I have added error checking for npm install, on self updates.

Added error checking at self update npm install

---

db.js

I did not have time last night, but today I have added alternate mysql/mariadb db name support to autobackups as well

Support different db names

---

db.js

I have added mysql/mariadb support to `getBackupConfig`

Added mysql/mariadb to getBackupConfig

---

meshctrl.js

This allows users to change the mode/flags for generating an invite link (0, 1 or 2).

Add flags arg for GenerateInviteLink

---

translate/translate.json

Dutch language update 0.8.57

---

db.js

This is a bit of code cleanup around making the mongodump command for auto-backups

Refactor mongodump command

---

meshcentral.js
meshuser.js

I've factored out logging to mesherrors.txt into its own method. I think this is useful for logging caught exceptions, instead of just printing to console. This can improve user's ability to report bugs.
I have started the intial refactoring of meshuser. I have added the command table in the same style and created handlers for `lastconnect` and `serverconsole`.
Feel free to leave any feedback of course.

Refactor meshuser

---

meshctrl.js

Resolves #2891
Implements displaying netif2 info in meshctrl 'deviceinfo'

Added netif2 to meshctrl deviceinfo

---

meshuser.js

Created handlers for 'getsysinfo' and 'getnetworkinfo'
I have introduced a new function for multiple lines of duplicate code in 'lastconnect', 'getsysinfo' and 'getnetworkinfo'

Refactoring meshuser

---

meshuser.js

Added command handler functions

Added meshuser command handler functions

---

translate/translate.json

Dutch language update 0.8.85

---

translate/translate.json

Fixed translation errors and added missing translations.

German translation update

---

meshuser.js

I have added some additional server command handlers.

Added server command handler functions

---

certoperations.js

Bugfix certoperations joinpath #3005

---

views/default-mobile.handlebars

Did some work to make it stop crashing agents and made it actually usable to some degree. Doesn't work *that* well in Firefox on mobile but it works fine in chrome (the Firefox issues were already there before).
Let me know what you think
Fixes #2814
Closes #2478

Mobile terminal improvements

---

meshuser.js

This continues the factorization of meshuser. Sorry it has been a while, I have been quite busy the past few months.
Summary
I have created command handler functions for the following:
- adduser
- adduserbatch
- addusertousergroup
- removeuserfromusergroup
- authcookie
- urlargs
- intersession
- logincookie
- changelang
- changeemail
- verifyemail
In the process, I fixed a number of use before assignment errors, and simplified removeuserfromusergroup a bit.

Factorize meshuser

---

docker/Dockerfile
docker/config.json.template
docker/readme.md
docker/startup.sh

Changes to docker file to fix issues related to plugins, https://github.com/ryanblenis/MeshCentral-ScriptTask/issues/23
Added more options to be used as enviroment variables for the docker image

Docker fixes and improvements

---

mpsserver.js

I have seen an interesting behavior on AMT 15 Dell platform, where AMT sends a keepalive to MPS (CIRA) every 90secs. Default timeout on MPS is 90 secs, and as a result socket timeout is triggered and MPS kills (ends) CIRA socket connection. Within few seconds, AMT device connects back to MPS but again timeout is triggered (and this happens continuously forever).
All other AMT devices by default send keepalive message every 30secs (tested this behavior on AMT 11, 12, 14 and AMT 15 versions).
I've added KEEPALIVE_OPTIONS_REQUEST logic to MPS so we can synchronize the keepalive time (i.e., to 30secs) across all devices.
Specification link: https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/HTMLDocuments/MPSDocuments/Intel%20AMT%20Port%20Forwarding%20Protocol …

Add KEEPALIVE_OPTIONS_REQUEST message support to mpserver

---

meshuser.js

Added function handlers for the following:
- updateUserImage
- getcookie
- smsuser
- emailuser
- getClip
- setClip
Bug fix in updateUserImage:
`allTargetGroups` was not declared, so  `if (allTargetGroups) {  ...` causes
```
ReferenceError: allTargetGroups is not defined
```
I added `var allTargetGroups = chguser.groups;`.
Other changes:
smsuser has an unused variable `errId`, which I removed. It now works the same as emailuser.

Factor meshuser

---

meshuser.js

I have added function handlers for the following server commands:
- updateAgents
- trafficstats
- trafficdelta
- report
Other improvements
1. I took the older `obj.send()`, which has been commented out since at least 2018, and re-implemented it for the current design. `obj.send()` now performs the `try { ws.send(JSON.stringify(object)); } catch(e) {}` which is typical for most server commands.
Lines in the command handlers which looked like
```javascript
try { ws.send(JSON.stringify({ action: 'lastconnects', lastconnects: response, tag: command.tag })); } catch (ex) { }
```
are now much cleaner to read:
```javascript
obj.send({ action: 'lastconnects', lastconnects: response, tag: command.tag });
```
2. I have given each report type a dedicated function from the `report` command. What was …

Factoring meshuser

---

webserver.js

Handle ldap on 'error'

---

translate/translate.json

Just update of missing translations.

Polish translation 0.9.72 update

---

.gitignore
.vscode/launch.json
public/styles/style.css
translate/translate.json
views/default.handlebars

Just making a tiny first step to check if we can help you in some places bringing this great project forward....

Small fix default.handlebars move Logout-Bar-Style to style.css

---

translate/translate.json

Fix typo & update translations

Dutch language update 0.9.72

---

translate/translate.json

Type=Tippen and Sharing-Mode = Modus

German translation for #3532

---

translate/translate.json

https://github.com/Ylianst/MeshCentral/issues/3532

Updated type in Polish translation

---

translate/translate.json

- all missing Russian lines added 
- many out of context, word order and declension errors fixed.

Russian language update and fixes

---

meshcentral-config-schema.json

Swapped the maxFiles and folderName data types for webDAV and Google Drive backup uploads

Update backup data types in config schema

---

meshcentral-config-schema.json

Allow IPs, Domain Names or CloudFlare and provide example.

Add description to TrustedProxy configuration

---

translate/translate.json

Update Polish translation

---

translate/translate.json

Dutch language update 0.9.95

---

translate/translate.json

Dutch language update pre 0.9.96

---

common.js
meshuser.js
views/default-mobile.handlebars
views/default.handlebars
webserver.js

Validate user email domain when adding a new user

New account email domains

---

translate/translate.json

Fixed some translations from earlier commits

Dutch langauge update 1.0.5

---

translate/translate.json

morexxx1, 2, 3, is not clear where its for.
SSH-User+Key+Pass, i assume pass is short for password,
clearify please

Dutch language update 1.0.20

---

translate/translate.json

Update Polish translation to 1.0.23 and some semantic changes.

Update Polish translation to 1.0.23

---

translate/translate.json

Restored formatting after polish translation

Dutch language update 1.0.23

---

db.js

Handle case of empty meshes list for SQL query

---

docs/docs/meshcentral/debugging.md

Are there other commands that would be useful listing? Where is that info?

docs - debugging agents

---

docs/docs/meshcentral/debugging.md

Adding info from https://github.com/Ylianst/MeshCentral/pull/4176

docs - adding more debug

---

db.js

I would imagine these queries could be used/adapted for PostgreSQL also, but I don't have a Postgres server in my environment currently to test.

Expire old entries for MariaDB/MySQL

---

translate/translate.json

+ corrected polish translation layout

Dutch translation update 1.0.41

---

.github/workflows/release.yml

**DO NOT MERGE UNTIL YOUR HAVE DONE THE FOLLOWING BELOW FIRST!**
**THIS IS REQUIRED OTHERWISE GITHUB FAILS DUE TO TOO MANY COMMITS**
1. CREATE A TAG FOR THE LATEST VERSION - E.G `1.0.45`
2. CREATE A MANUAL RELEASE FROM THE TAG WITH THE SAME VERSION NUMBER - E.G `1.0.45`
3. THEN MERGE THIS PR

create new release on every new version

---

webserver.js

Added missing equals sign when checking null session

Fix for #4307

---

.github/workflows/docker.yml
.github/workflows/release.yml
docker/Dockerfile

EDIT2: all good to go now 17:51 22/07/22
DO NOT MERGE UNTIL YOU HAVE DONE THE FOLLOWING:
1. create a personal access token with `write:packages` and `repo` scopes and an `unlimited` expiration (otherwise you will have to generate a new one every 30 days)
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
2. then add the personal access token to a secret in the repo called `MY_TOKEN`
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
3. merge this PR
4. Change package.json version to trigger a new version (this will trigger the automatic release notes, and then trigger the docker build)
5. once the docker image has been built and published (about 15mins), view the …

add docker release action

---

docker/BUILD.md
docker/readme.md

move docker build to serperate doc file and change repo to use github

add docker build docs

---

docker/readme.md

Modified the docker-compose example files to use the official (automatically created) docker images

modified docker-compose examples to use the official docker image

---

webserver.js

I found some issues straight away, if a user was not in a required group it would run a stolen (not present) function from the LDAP section, I replaced it with a bit of code from the 'no new users allowed' section so the code it reports to the login page is wrong.  
Other than that this contains some general cleanup of the debug lines, a check to see if groups are enabled before adding it to the requested OIDC scope, and a small fix to the logic in the filter section so that it will work as expected.

Bug fix for OIDC Groups

---

docs/docs/meshcentral/SSLnletsencrypt.md

added a link to the config schema

Edit le instructions

---

translate/translate.json

Dutch language update 1.0.85

---

docs/docs/messaging/index.md

For self-hosting your own ntfy server with ACL support

ntfy in documentation

---

.github/workflows/docker.yml

#4737 
I followed the docker documentation, but I haven't tested it myself because I don't even know if I can test it myself (I'd be happy to be pointed in the right direction, though)

Github Actions: Building Multiplatform Docker image (AMD64 and ARM64)

---

views/sharing-mobile.handlebars
views/sharing.handlebars

Connecting to a terminal in a share currently results in a successful connection with nothing displayed on the terminal. This fixes that issue.
Similar to #4668

Fix xterm in shared terminals

---

docs/docs/install/install2.md

Hello,
I was [told here](https://github.com/Ylianst/MeshCentral/issues/4918) to give it a try to patch the documentation to help users for restoring a backup :)
Here is what I did with succes in my last Ubuntu 20.04 installation of Meshcentral

Add documentation for restoring backup in Ubuntu

---

translate/translate.json

Update Polish translation for v1.1.3

Update Polish translation for v1.1.3

---

translate/translate.json

Most of the keys above should not be translated here.

fix(translate): some wrong zhs words

---

sample-config.json

Reference Issues/PRs
Issues #3245 / #3296
what does this implement fix? Explain your changes. setting skipChallengeVerification to true by default to save sometime when setting up a certificate
any other comments
I can see that this problem has been solved and a suggestion to make it easier I think is to set "skipChallengeVerification": true by default.

Update sample-config.json let's encrypt section

---

public/styles/style.css
views/default.handlebars

Reverts Ylianst/MeshCentral#5140

Revert "Remove code redundancy"

---

views/default.handlebars

update star limit to 200

---

meshcentral-config-schema.json

to only **all** some users -> to only **allow** some users
time **the** to wait for a 2FA token -> time ~~the~~ to wait for a 2FA token

Update meshcentral-config-schema.json (fix typos)

---

meshcentral-config-schema.json

This way it is easier to edit and maintain.
An idea: to use a linter in your pipeline to get this done automatically.
Another idea (to be consider in a separated commit-issue): add descriptions and default value for each possible field. I found this details to be important because this file is the main resource about how to use and configure the system.

Update meshcentral-config-schema.json (change formatting)

---

views/default-mobile.handlebars

fixes an issue on mobile devices using ssh connect

fix mobile ssh utf8

---

meshcentral-config-schema.json

this fixes an issue where all values where being listed under `deviceMeshRouterLinks`
also a bit of formatting to read easier

fix meshcentral-config-schema.json

---

db.js

Fix nedbtodb and sqlite

---

docker/startup.sh

only numbers and letters in session key docker

---

meshcentral.js
webrelayserver.js
webserver.js

update passport to 0.6.0

---

meshcentral.js

delete user messaging on resetaccount

---

certoperations.js

Fixes #5316 - fix a bug where `r.certs[0].md.algorithm` could be null

if amt algorithm use it

---

meshmessaging.js

check msghandle for messaging

---

views/default.handlebars

fix multidisplay multimonitor

---

views/player.handlebars
views/xterm.handlebars

fix writeUtf8 for ssh player

---

meshuser.js

deny sspi and ldap password change

---

views/default-mobile.handlebars
views/default.handlebars

this helps with mobile users and a BLANK page,
allowing clicking the header text to go to the device view

add header onclick event

---

views/agentinvite.handlebars

fix android url

---

views/default.handlebars

add missing openwrt x86-64

---

docs/mkdocs.yml

add missing messaging docs link

---

meshuser.js
views/default.handlebars

show server config for admins

---

docs/docs/meshcentral/config.md
docs/docs/messaging/index.md
meshcentral-config-schema.json
meshmessaging.js
sample-config-advanced.json

add authorization to ntfy

---

views/default.handlebars
views/login.handlebars
views/login2.handlebars
webserver.js

fix pwa manifest

---

docs/docs/meshcentral/config.md
meshcentral-config-schema.json
sample-config-advanced.json
views/default-mobile.handlebars
views/default.handlebars
webserver.js

hidePowerTimeline

---

meshuser.js
views/default.handlebars

add tags to csv

---

agents/meshcore.js
views/default-mobile.handlebars
views/default.handlebars

add bios serial for windows

---

views/default.handlebars

add scroll to top button

---

meshcentral.js

deny resetaccount pass change with external auth

---

agents/meshcore.js
views/default.handlebars

add bios mode uefi or legacy

---

agents/meshcore.js

to be used with https://github.com/Ylianst/MeshAgent/pull/203

ignore if client sent new identifiers

---

views/default.handlebars

fix random files connect button vanishing

---

views/default-mobile.handlebars
views/default.handlebars

enable ssh connect for windows

---

views/default-mobile.handlebars
views/default.handlebars

Some VMs return a blank BankLabel so show Unknown if undefined 

fix undefined memory label

---

views/default-mobile.handlebars
views/default.handlebars

add linux memory

---

views/default-mobile.handlebars

fix backspace mobile ssh

---

.github/workflows/docker.yml

this will make a `master` docker image on every `master` push,
allows users to get latest features/fixes quicker until a new npm is released
`ghcr.io/ylianst/meshcentral:master`

make dev master docker image

---

views/default.handlebars

fix graph needs destroying

---

views/default.handlebars

add tags to columns

---

views/default.handlebars

add display sizes to files

---

meshuser.js

dont allow duplicate emails on admin create

---

agents/modules_meshcore/sysinfo.js
public/styles/style.css
views/default.handlebars

Fixes #2304
Fixes #2596
(SQUASH AND MERGE)
**WINDOWS:**
**RPI LINUX:**
**MULTILINE:**

add hover title to temps and more sensors

---

views/default.handlebars

Fixes #4740
no mobile view as no room for more buttons really
please check @Ylianst

add Go To Folder

---

views/default.handlebars

Fixes #3885
**SQUASH AND MERGE**

add last boot up time for windows

---

agents/meshcore.js

Fixes #4422
**SQUASH AND MEGRE**

fix runcommands missing data

---

agents/meshcore.js
public/scripts/common-0.0.1.js
views/default.handlebars

Fixes #2767
**SQUASH AND MERGE**

add agent psinfo

---

db.js

Fixes #5465
https://github.com/Ylianst/MeshCentral/discussions/5464

fix mariadb parsing with mysql

---

meshuser.js

Fixes #4753 
it wasnt adding the domain to the nodeid so was deleting nothing?

fix removedevice with meshctrl

---

views/default.handlebars

fix messaging handle string too long

---

views/default-mobile.handlebars

add lastbootuptime to mobile

---

meshdesktopmultiplex.js
meshrelay.js

fix sessionrecording always indexing

---

db.js

fix postgres sqlbatch

---

db.js

Fixes #4995
When postgresql it works again I could try to fix too. #5511
Test Plugin: [ https://raw.githubusercontent.com/ryanblenis/MeshCentral-Sample/master/config.json](url)

Fix plugins installation for MySQL/MariaDB/SQLite

---

webserver.js

fix agentaliasdns display

---

db.js

- Fix plugins installation for PostgreSQL
- Changed setPluginStatus for fix a bug when upgrade plugins. Now setPluginStatus set status value without call getPlugin and updatePlugin.
Test Plugin: [https://raw.githubusercontent.com/ryanblenis/MeshCentral-Sample/master/config.json](https://raw.githubusercontent.com/ryanblenis/MeshCentral-Sample/master/config.json)

Fix plugins installation for PostgreSQL

---

views/default.handlebars

Fixes #2964
Signed-off-by: si458 simonsmith5521@gmail.com

add windows av/update/firewall to columns

---

readme.md

These rooms have quite a few people in them!

Share unofficial chatrooms

---

docs/docs/meshcentral/config.md
meshcentral-config-schema.json
public/styles/style.css
sample-config-advanced.json
views/default.handlebars
webserver.js

showNotesPanel in device view

---

docs/docs/meshcentral/config.md
meshcentral-config-schema.json
views/default-mobile.handlebars
views/default.handlebars
webserver.js

Added device group name to search results as config option (#5536)

---

dependencies.txt
meshcentral.js
package.json

update ua-parser-js to 1.0.37

---

views/default.handlebars

fix edit messaging using wrong user

---

docs/docs/meshcentral/config.md
docs/docs/messaging/index.md
meshcentral-config-schema.json
meshmessaging.js
meshuser.js
views/default.handlebars

Fixes #5564
**MUST SQUASH AND MERGE**

add slack webhooks messaging

---

agents/meshcore.js
views/default-mobile.handlebars
views/default.handlebars

Add windows linux mac uptime

---

docs/docs/meshcentral/tipsntricks.md

should be able to close https://github.com/Ylianst/MeshCentral/issues/1965, https://github.com/Ylianst/MeshCentral/issues/336 and https://github.com/Ylianst/MeshCentral/issues/1776 as added docs "you can go in the config.json and set "ldapuserkey" to "sAMAccountName" and it would have the same effect as the change you made."

updated tipsntricks

---

agents/meshcore.js
views/default.handlebars

add old style alertbox

---

agents/meshcore.js
agents/modules_meshcore/computer-identifiers.js

move identifiers to server side to allow future updates

---

meshuser.js

add tpm to csv

---

agents/meshcore.js
agents/modules_meshcore/win-info.js
meshagent.js
views/default-mobile.handlebars
views/default.handlebars

add Defender for Windows Server

---

views/default.handlebars

add tools resizable

---

views/default.handlebars

add different notification types

---

meshcentral-config-schema.json
sample-config-advanced.json
views/agentinvite.handlebars
webserver.js

allow setting meshcentral assistant type for agentinvites

---

agents/modules_meshcore/computer-identifiers.js

add bitlocker recoverypassword to sysinfo

---

views/default.handlebars

add middle click to open in new tab

---

agents/meshcore.js

escape apostrophes in privacybar realname

---

agents/meshcore.js
meshctrl.js
views/default.handlebars

add timeout to message box notifications

---

webserver.js

Fix meshcentral assistant monitor mode always using direct connect mode

---

.gitignore
docker/Dockerfile
meshcentral.js
package-lock.json
package.json
translate/translate.js

Fixes #5640
**PLEASE REVIEW CODE FIRST**

Fix package installs and set node 20 for docker

---

amtmanager.js
meshcentral.js

fix amt powerstate and timer

---

views/default.handlebars

add multiple file download by check boxes

---

agents/meshcore.js
views/default-mobile.handlebars
views/default.handlebars

add dns servers to details tab

---

agents/meshcore.js
views/default.handlebars

show rdp port on button and set rdpport in console

---

views/agentinvite.handlebars

add linux binary to agentinvite

---

agents/meshcore.js
views/default.handlebars

add extra services information

---

views/default-mobile.handlebars

add android apk to mobile ui

---

apprelays.js

fix numlock sending extended keys incorrectly

---

agents/meshcore.js

Might help with this issue here
https://www.reddit.com/r/MeshCentral/comments/1ab9i6z/how_uninstall_meshagent_from_my_laptop_that/

add application location to info

---

agents/meshcore.js
public/styles/style.css
views/default.handlebars

add drive names and icons to files

---

public/scripts/agent-redir-ws-0.1.1.js
views/default.handlebars

show latency in remote/terminal every 10 secs

---

views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/1332

fix latency bouncing monitors

---

views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/4860

fix account pic transparency

---

certoperations.js

Fixes #5595
thank you @fernandogobah for donating a machine which was having the issue!

use accelerator regardless of cpu core count

---

agents/modules_meshcore/win-info.js

Fixes https://github.com/Ylianst/MeshCentral/issues/1538

add installdate to installedapps

---

apprelays.js

Fixes https://github.com/Ylianst/MeshCentral/pull/5727
Fixes https://github.com/Ylianst/MeshCentral/issues/5785
Fixes https://github.com/Ylianst/MeshCentral/issues/3475

fix agentping

---

docs/docs/install/install2.md
docs/docs/meshcentral/agents.md

Where are all the other .msh options we can add to docs?

Docs update on skipmaccheck

---

translate/translate.json

Also fix some mistake made with nl translation.

Update Polish translation for Meshcentral v 1..1.21

---

translate/translate.json

Polish translation - Fix typo

---

views/default.handlebars

fix translation values in details tab

---

agents/meshcore.js
agents/modules_meshcore/computer-identifiers.js
translate/translate.json
views/default-mobile.handlebars
views/default.handlebars

add Capacity Remaining

---

agents/meshcore.js
agents/modules_meshcore/computer-identifiers.js
translate/translate.json
views/default-mobile.handlebars
views/default.handlebars

show cd-rom as volume

---

translate/translate.json

NOTE: i saw a lot off undefined strings, please review
example: [[[SERVERNAME]]] - Account Invitation\nAn account was created for you on server [[[SERVERNAME]]] ([[[SERVERURL]]]/[[[URLARGS1]]]), you can access it now with username "[[[ACCOUNTNAME]]]" and password "[[[PASSWORD]]]".\n~\nBest regards,\n~[[[USERNAME]]]

Dutch language update 1.1.21

---

agents/modules_meshcore/computer-identifiers.js
views/default-mobile.handlebars
views/default.handlebars

show macos memory and memory slots
show macos storage drives

add mac memory/storage

---

translate/translate.json

Dutch language update 1.1.21 V2

---

meshctrl.js
translate/translate.json
views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/5341

add no consent to guest sharing

---

agents/meshcore.js
translate/translate.json
views/default.handlebars

add unzip to files

---

meshctrl.js

add relay and port to devicesharing in meshctrl.js

---

pluginHandler.js

Some files were created with permissions of 0o000. You could not even read them.
Thank you for merging my previous pull request so quickly. 
Sorry I tested it so poorly. I should test longer before creating a pull request.

Bugfix to merged pull request #5865

---

meshcentral.js

I had some bad merging in #5856. This is just being reverted to how it was setup in #5332

Update Passport version in meshcentral.js - Fix bad merge

---

webserver.js

I added some additional logging and fixed a bug with how the strategy info was saved for later causing multiple instances of the OIDC strategy on different domains to overwrite each other's URLs causing problems with logging in and logging out depending on the domain.

Login/logout bugfix for OIDC strategy.

---

meshcentral.js
webserver.js

More minor fixes, this one is only formatting (e.g. spaces vs tabs, different return characters, etc.)
Some are from #5856 but some are from further back.

Fix formatting issues from merging

---

agents/meshcore.js

Fixes https://github.com/Ylianst/MeshCentral/issues/249

wake mac screen with caffeinate

---

meshuser.js

add biosSerial/biosMode to csv

---

docs/docs/meshcentral/assistant.md
docs/docs/meshcentral/codesigning.md
docs/docs/meshcentral/customization.md
docs/docs/meshcentral/debugging.md
docs/docs/meshcentral/faq.md
docs/docs/meshcentral/plugins.md

A quick pass on the meshcentral docs folder for readability issues.

Various grammar, spelling, and clarity issues.

---

views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/5902

set flatpickr to 1 minute increments

---

db.js
meshuser.js
views/default.handlebars

add filter for events

---

db.js

Fixes https://github.com/Ylianst/MeshCentral/issues/5263

check db exists first before creating in postgres

---

translate/translate.json
views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/1200

add user import via csv file

---

meshuser.js
views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/5854

fix name display for oauth

---

views/default-mobile.handlebars

add open web link to mobile ui

---

agents/meshcore.js
agents/modules_meshcore/computer-identifiers.js
meshagent.js
translate/translate.json
views/default.handlebars

Fixes
https://github.com/Ylianst/MeshCentral/issues/2435
https://github.com/Ylianst/MeshCentral/issues/5912
https://github.com/Ylianst/MeshCentral/issues/4207

add lastbootuptime to columns and device powered on event

---

apprelays.js
meshuser.js

Fixes https://github.com/Ylianst/MeshCentral/issues/5994

unEscape ssh/rdp creds from db

---

common.js
meshctrl.js

Fixes https://github.com/Ylianst/MeshCentral/issues/6000

add missing rights to meshctrl and meshServerRightsArrayToNumber

---

webserver.js

Fixes https://github.com/Ylianst/MeshCentral/issues/5923

fix authStrategyFlags using wrong domain

---

webserver.js

Fixes https://github.com/Ylianst/MeshCentral/issues/5923

fix custom public folders for dns domains

---

meshcentral.js

Fixes https://github.com/Ylianst/MeshCentral/issues/6022

translation fixes for meshcentral-data-domain

---

views/default-mobile.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/6033

add run commands to mobile ui

---

meshcentral.js
package.json

set min to node 16

---

translate/translate.json
views/default-mobile.handlebars
views/default.handlebars

Fixes https://github.com/Ylianst/MeshCentral/issues/6102

fix keyboard shortcuts and add restore default keyboard shortcuts

---

meshcentral-config-schema.json
sample-config-advanced.json
views/default-mobile.handlebars
views/default.handlebars
webserver.js

Fixes https://github.com/Ylianst/MeshCentral/issues/6170

add userSessionsSort for session sorting

---

webserver.js

fix meshcentral-web-domain translate displaying

---

views/default.handlebars

fix filter refilling in chrome and safari

---

dependencies.txt
meshcentral.js
package-lock.json
package.json

update ws to 8.17.1

---

db.js
meshcentral-config-schema.json
meshcentral.js
sample-config-advanced.json

add s3 autobackup support

---

amtmanager.js
meshuser.js
views/default.handlebars

Hello !
This commit add support for PXE booting from the webui and with LibMeshCtrl.
It has been tested on a Dell Optiplex 7400 AIO (Intel AMT 16)
Feel free to ask any questions or modifications :open_hands:

AMT: Add support for PXE reboot/power

---

meshagent.js

https://github.com/Ylianst/MeshCentral/issues/2095#issuecomment-2276360509

fix orphanagentuser toLowerCase()

---

docs/docs/meshcentral/openidConnectStrategy.md

add annotation about using own IDP, CA and Docker

---

db.js

Put dbdumpfile back in root of zip instead of meshcentral-data subfolder and normalize some more
For completeness added normalize to the dumpcommand functions.
Fixes #6481

Put dbdumpfile in root of zip

---

db.js

Fixes the filter in the node event tab

Add forgotten space in sqlite query GetNodeEventsWithLimit

---

db.js
dependencies.txt
meshcentral.js
package.json

Fixes https://github.com/Ylianst/MeshCentral/issues/6503

use @seald-io/nedb for node23 support

---

pluginHandler.js

chore: update pluginHandler.js

---

certoperations.js

Fixes multi domain using default domain cert without trying to recreate for new domains

---

meshcentral-config-schema.json
meshcentral.js
monitoring.js

add prometheus metrics

---

webserver.js

include username for amt direct connect/kvm

To improve auditing during AMT direct connect

---

meshuser.js

A little update to the info command, added the h option to make the numbers a bit more readable. Converts elapsed time in seconds to days hours minutes seconds and memory to Mb.
@si458 Do you know why all the try's are there? Maybe could be removed?

Update console info command

---

meshcentral-config-schema.json
public/styles/style-bootstrap.css
public/styles/style.css
sample-config-advanced.json
views/default.handlebars
views/default3.handlebars
webserver.js

Fixes https://github.com/Ylianst/MeshCentral/issues/6660
```
{
"domains": {
"showModernUIToggle": true
}
}
```

UI Toggle between Classic and Modern

---

agents/meshcore.js
meshcentral-config-schema.json
meshdesktopmultiplex.js
meshrelay.js
meshuser.js
sample-config-advanced.json

Fixes #6158
NOTES:
1.  2 hours to implement just the desktop feature
2. 30 mins for terminal implement
3. 30 mins for files implement

autoAcceptIfNoUser

---

agents/meshcore.js
meshctrl.js

Fix is related to issue described here https://github.com/Ylianst/MeshCentral/issues/6743

prevent runcommand with --reply from terminating other ws connections

---

monitoring.js

Add metric collectors from plugins.
resolves #6776

Add collectors to monitoring

---

meshcentral.js

[chore] bump pg npm module to 8.14.1

---

meshcentral.js

PR related to: https://github.com/Ylianst/MeshCentral/issues/6910

[chore] bump semver to 7.7.1

---

amt/amt-redir-mesh.js
amt/amt-wsman-comm.js
amtscanner.js
webserver.js

use minversion tlsv1 to fix older amt issues

---

db.js

Text was incorrect and misleading regarding path, as the error is a more general failure. #7094

Changed sqldump errortext

---

db.js
meshcentral.js

Make autobackup: false disable all backup functions and remove cmd from checkbackup error message.
Fixes #7221 and #7056

Fix autobackup check

---

db.js

- add missing postgresql info
- properly handle autobackup switch
Fixes additional observation #7221

Fix backupconfig info

---

public/styles/style-bootstrap.css
views/default3.handlebars

This PR updates "Remote Desktop Setting" dialog style

[Modern UI] Update Remote Desktop Settings dialog style
